<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetGameVersion>1.6</TargetGameVersion>
    <InternalModVersion>1.0</InternalModVersion>
    <VersionPrefix>$(TargetGameVersion).$(InternalModVersion)</VersionPrefix>
    <OutputType>Library</OutputType>
    <RootNamespace>RJWFuta</RootNamespace>
    <AssemblyName>RJWFuta</AssemblyName>
    <TargetFramework>net472</TargetFramework>
    <Optimize>true</Optimize>
    <OutputPath>..\1.6\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <NoWarn>$(NoWarn);CS0169;CS0649</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(TargetGameVersion).*" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="RJW">
      <HintPath>..\..\..\games\SteamLibrary\steamapps\common\RimWorld\Mods\rjw-master-fork\1.6\Assemblies\RJW.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
